Update EventParams.cs
No need to hide this code under !DISABLESTEAMWORKS define
Otherwise, with define DISABLESTEAMWORKS, you get compile errors:
- Base/Interfaces.cs(17,26): error CS0246: The type or namespace name `InitResultEventArgs' could not be found. Are you missing an assembly reference?
- Base/Interfaces.cs(18,27): error CS0246: The type or namespace name `GetAppUsersEventArgs' could not be found. Are you missing an assembly reference?
- Base/SocialNetworkBase.cs(25,36): error CS0246: The type or namespace name `InitResultEventArgs' could not be found. Are you missing an assembly reference?
- Base/SocialNetworkBase.cs(35,28): error CS0246: The type or namespace name `LoginResultEventArgs' could not be found. Are you missing an assembly reference?
- Base/SocialNetworkBase.cs(62,34): error CS0246: The type or namespace name `GetAppUsersEventArgs' could not be found. Are you missing an assembly reference?